// Current Date and Time (UTC): 2025-03-14 13:34:49
// Current User's Login: aorfile

import 'country_model.dart';

final List<Country> countries = [
  // Default/Most used countries first
  Country(name: 'Ghana', flag: '🇬🇭', code: 'GH', dialCode: '+233'),
  Country(name: 'United States', flag: '🇺🇸', code: 'US', dialCode: '+1'),
  Country(name: 'United Kingdom', flag: '🇬🇧', code: 'GB', dialCode: '+44'),

  // Alphabetically ordered countries
  Country(name: 'Afghanistan', flag: '🇦🇫', code: 'AF', dialCode: '+93'),
  Country(name: 'Albania', flag: '🇦🇱', code: 'AL', dialCode: '+355'),
  Country(name: 'Algeria', flag: '🇩🇿', code: 'DZ', dialCode: '+213'),
  Country(name: 'Andorra', flag: '🇦🇩', code: 'AD', dialCode: '+376'),
  Country(name: 'Angola', flag: '🇦🇴', code: 'AO', dialCode: '+244'),
  Country(name: 'Antigua & Barbuda', flag: '🇦🇬', code: 'AG', dialCode: '+1'),
  Country(name: 'Argentina', flag: '🇦🇷', code: 'AR', dialCode: '+54'),
  Country(name: 'Armenia', flag: '🇦🇲', code: 'AM', dialCode: '+374'),
  Country(name: 'Australia', flag: '🇦🇺', code: 'AU', dialCode: '+61'),
  Country(name: 'Austria', flag: '🇦🇹', code: 'AT', dialCode: '+43'),
  Country(name: 'Azerbaijan', flag: '🇦🇿', code: 'AZ', dialCode: '+994'),
  Country(name: 'Bahamas', flag: '🇧🇸', code: 'BS', dialCode: '+1'),
  Country(name: 'Bahrain', flag: '🇧🇭', code: 'BH', dialCode: '+973'),
  Country(name: 'Bangladesh', flag: '🇧🇩', code: 'BD', dialCode: '+880'),
  Country(name: 'Barbados', flag: '🇧🇧', code: 'BB', dialCode: '+1'),
  Country(name: 'Belarus', flag: '🇧🇾', code: 'BY', dialCode: '+375'),
  Country(name: 'Belgium', flag: '🇧🇪', code: 'BE', dialCode: '+32'),
  Country(name: 'Belize', flag: '🇧🇿', code: 'BZ', dialCode: '+501'),
  Country(name: 'Benin', flag: '🇧🇯', code: 'BJ', dialCode: '+229'),
  Country(name: 'Bhutan', flag: '🇧🇹', code: 'BT', dialCode: '+975'),
  Country(name: 'Bolivia', flag: '🇧🇴', code: 'BO', dialCode: '+591'),
  Country(name: 'Bosnia', flag: '🇧🇦', code: 'BA', dialCode: '+387'),
  Country(name: 'Botswana', flag: '🇧🇼', code: 'BW', dialCode: '+267'),
  Country(name: 'Brazil', flag: '🇧🇷', code: 'BR', dialCode: '+55'),
  Country(name: 'Brunei', flag: '🇧🇳', code: 'BN', dialCode: '+673'),
  Country(name: 'Bulgaria', flag: '🇧🇬', code: 'BG', dialCode: '+359'),
  Country(name: 'Burkina Faso', flag: '🇧🇫', code: 'BF', dialCode: '+226'),
  Country(name: 'Burundi', flag: '🇧🇮', code: 'BI', dialCode: '+257'),
  Country(name: 'Cambodia', flag: '🇰🇭', code: 'KH', dialCode: '+855'),
  Country(name: 'Cameroon', flag: '🇨🇲', code: 'CM', dialCode: '+237'),
  Country(name: 'Canada', flag: '🇨🇦', code: 'CA', dialCode: '+1'),
  Country(name: 'Cape Verde', flag: '🇨🇻', code: 'CV', dialCode: '+238'),
  Country(
    name: 'Central African Republic',
    flag: '🇨🇫',
    code: 'CF',
    dialCode: '+236',
  ),
  Country(name: 'Chad', flag: '🇹🇩', code: 'TD', dialCode: '+235'),
  Country(name: 'Chile', flag: '🇨🇱', code: 'CL', dialCode: '+56'),
  Country(name: 'China', flag: '🇨🇳', code: 'CN', dialCode: '+86'),
  Country(name: 'Colombia', flag: '🇨🇴', code: 'CO', dialCode: '+57'),
  Country(name: 'Comoros', flag: '🇰🇲', code: 'KM', dialCode: '+269'),
  Country(name: 'Congo', flag: '🇨🇬', code: 'CG', dialCode: '+242'),
  Country(name: 'Costa Rica', flag: '🇨🇷', code: 'CR', dialCode: '+506'),
  Country(name: 'Croatia', flag: '🇭🇷', code: 'HR', dialCode: '+385'),
  Country(name: 'Cuba', flag: '🇨🇺', code: 'CU', dialCode: '+53'),
  Country(name: 'Cyprus', flag: '🇨🇾', code: 'CY', dialCode: '+357'),
  Country(name: 'Czech Republic', flag: '🇨🇿', code: 'CZ', dialCode: '+420'),
  Country(name: 'Denmark', flag: '🇩🇰', code: 'DK', dialCode: '+45'),
  Country(name: 'Djibouti', flag: '🇩🇯', code: 'DJ', dialCode: '+253'),
  Country(name: 'Dominica', flag: '🇩🇲', code: 'DM', dialCode: '+1'),
  Country(name: 'Dominican Republic', flag: '🇩🇴', code: 'DO', dialCode: '+1'),
  Country(name: 'Ecuador', flag: '🇪🇨', code: 'EC', dialCode: '+593'),
  Country(name: 'Egypt', flag: '🇪🇬', code: 'EG', dialCode: '+20'),
  Country(name: 'El Salvador', flag: '🇸🇻', code: 'SV', dialCode: '+503'),
  Country(
    name: 'Equatorial Guinea',
    flag: '🇬🇶',
    code: 'GQ',
    dialCode: '+240',
  ),
  Country(name: 'Eritrea', flag: '🇪🇷', code: 'ER', dialCode: '+291'),
  Country(name: 'Estonia', flag: '🇪🇪', code: 'EE', dialCode: '+372'),
  Country(name: 'Ethiopia', flag: '🇪🇹', code: 'ET', dialCode: '+251'),
  Country(name: 'Fiji', flag: '🇫🇯', code: 'FJ', dialCode: '+679'),
  Country(name: 'Finland', flag: '🇫🇮', code: 'FI', dialCode: '+358'),
  Country(name: 'France', flag: '🇫🇷', code: 'FR', dialCode: '+33'),
  Country(name: 'Gabon', flag: '🇬🇦', code: 'GA', dialCode: '+241'),
  Country(name: 'Gambia', flag: '🇬🇲', code: 'GM', dialCode: '+220'),
  Country(name: 'Georgia', flag: '🇬🇪', code: 'GE', dialCode: '+995'),
  Country(name: 'Germany', flag: '🇩🇪', code: 'DE', dialCode: '+49'),
  Country(name: 'Greece', flag: '🇬🇷', code: 'GR', dialCode: '+30'),
  Country(name: 'Grenada', flag: '🇬🇩', code: 'GD', dialCode: '+1'),
  Country(name: 'Guatemala', flag: '🇬🇹', code: 'GT', dialCode: '+502'),
  Country(name: 'Guinea', flag: '🇬🇳', code: 'GN', dialCode: '+224'),
  Country(name: 'Guinea-Bissau', flag: '🇬🇼', code: 'GW', dialCode: '+245'),
  Country(name: 'Guyana', flag: '🇬🇾', code: 'GY', dialCode: '+592'),
  Country(name: 'Haiti', flag: '🇭🇹', code: 'HT', dialCode: '+509'),
  Country(name: 'Honduras', flag: '🇭🇳', code: 'HN', dialCode: '+504'),
  Country(name: 'Hungary', flag: '🇭🇺', code: 'HU', dialCode: '+36'),
  Country(name: 'Iceland', flag: '🇮🇸', code: 'IS', dialCode: '+354'),
  Country(name: 'India', flag: '🇮🇳', code: 'IN', dialCode: '+91'),
  Country(name: 'Indonesia', flag: '🇮🇩', code: 'ID', dialCode: '+62'),
  Country(name: 'Iran', flag: '🇮🇷', code: 'IR', dialCode: '+98'),
  Country(name: 'Iraq', flag: '🇮🇶', code: 'IQ', dialCode: '+964'),
  Country(name: 'Ireland', flag: '🇮🇪', code: 'IE', dialCode: '+353'),
  Country(name: 'Israel', flag: '🇮🇱', code: 'IL', dialCode: '+972'),
  Country(name: 'Italy', flag: '🇮🇹', code: 'IT', dialCode: '+39'),
  Country(name: 'Jamaica', flag: '🇯🇲', code: 'JM', dialCode: '+1'),
  Country(name: 'Japan', flag: '🇯🇵', code: 'JP', dialCode: '+81'),
  Country(name: 'Jordan', flag: '🇯🇴', code: 'JO', dialCode: '+962'),
  Country(name: 'Kazakhstan', flag: '🇰🇿', code: 'KZ', dialCode: '+7'),
  Country(name: 'Kenya', flag: '🇰🇪', code: 'KE', dialCode: '+254'),
  Country(name: 'Kiribati', flag: '🇰🇮', code: 'KI', dialCode: '+686'),
  Country(name: 'Kuwait', flag: '🇰🇼', code: 'KW', dialCode: '+965'),
  Country(name: 'Kyrgyzstan', flag: '🇰🇬', code: 'KG', dialCode: '+996'),
  Country(name: 'Laos', flag: '🇱🇦', code: 'LA', dialCode: '+856'),
  Country(name: 'Latvia', flag: '🇱🇻', code: 'LV', dialCode: '+371'),
  Country(name: 'Lebanon', flag: '🇱🇧', code: 'LB', dialCode: '+961'),
  Country(name: 'Lesotho', flag: '🇱🇸', code: 'LS', dialCode: '+266'),
  Country(name: 'Liberia', flag: '🇱🇷', code: 'LR', dialCode: '+231'),
  Country(name: 'Libya', flag: '🇱🇾', code: 'LY', dialCode: '+218'),
  Country(name: 'Liechtenstein', flag: '🇱🇮', code: 'LI', dialCode: '+423'),
  Country(name: 'Lithuania', flag: '🇱🇹', code: 'LT', dialCode: '+370'),
  Country(name: 'Luxembourg', flag: '🇱🇺', code: 'LU', dialCode: '+352'),
  Country(name: 'Madagascar', flag: '🇲🇬', code: 'MG', dialCode: '+261'),
  Country(name: 'Malawi', flag: '🇲🇼', code: 'MW', dialCode: '+265'),
  Country(name: 'Malaysia', flag: '🇲🇾', code: 'MY', dialCode: '+60'),
  Country(name: 'Maldives', flag: '🇲🇻', code: 'MV', dialCode: '+960'),
  Country(name: 'Mali', flag: '🇲🇱', code: 'ML', dialCode: '+223'),
  Country(name: 'Malta', flag: '🇲🇹', code: 'MT', dialCode: '+356'),
  Country(name: 'Marshall Islands', flag: '🇲🇭', code: 'MH', dialCode: '+692'),
  Country(name: 'Mauritania', flag: '🇲🇷', code: 'MR', dialCode: '+222'),
  Country(name: 'Mauritius', flag: '🇲🇺', code: 'MU', dialCode: '+230'),
  Country(name: 'Mexico', flag: '🇲🇽', code: 'MX', dialCode: '+52'),
  Country(name: 'Micronesia', flag: '🇫🇲', code: 'FM', dialCode: '+691'),
  Country(name: 'Moldova', flag: '🇲🇩', code: 'MD', dialCode: '+373'),
  Country(name: 'Monaco', flag: '🇲🇨', code: 'MC', dialCode: '+377'),
  Country(name: 'Mongolia', flag: '🇲🇳', code: 'MN', dialCode: '+976'),
  Country(name: 'Montenegro', flag: '🇲🇪', code: 'ME', dialCode: '+382'),
  Country(name: 'Morocco', flag: '🇲🇦', code: 'MA', dialCode: '+212'),
  Country(name: 'Mozambique', flag: '🇲🇿', code: 'MZ', dialCode: '+258'),
  Country(name: 'Myanmar', flag: '🇲🇲', code: 'MM', dialCode: '+95'),
  Country(name: 'Namibia', flag: '🇳🇦', code: 'NA', dialCode: '+264'),
  Country(name: 'Nauru', flag: '🇳🇷', code: 'NR', dialCode: '+674'),
  Country(name: 'Nepal', flag: '🇳🇵', code: 'NP', dialCode: '+977'),
  Country(name: 'Netherlands', flag: '🇳🇱', code: 'NL', dialCode: '+31'),
  Country(name: 'New Zealand', flag: '🇳🇿', code: 'NZ', dialCode: '+64'),
  Country(name: 'Nicaragua', flag: '🇳🇮', code: 'NI', dialCode: '+505'),
  Country(name: 'Niger', flag: '🇳🇪', code: 'NE', dialCode: '+227'),
  Country(name: 'Nigeria', flag: '🇳🇬', code: 'NG', dialCode: '+234'),
  Country(name: 'North Korea', flag: '🇰🇵', code: 'KP', dialCode: '+850'),
  Country(name: 'North Macedonia', flag: '🇲🇰', code: 'MK', dialCode: '+389'),
  Country(name: 'Norway', flag: '🇳🇴', code: 'NO', dialCode: '+47'),
  Country(name: 'Oman', flag: '🇴🇲', code: 'OM', dialCode: '+968'),
  Country(name: 'Pakistan', flag: '🇵🇰', code: 'PK', dialCode: '+92'),
  Country(name: 'Palau', flag: '🇵🇼', code: 'PW', dialCode: '+680'),
  Country(name: 'Palestine', flag: '🇵🇸', code: 'PS', dialCode: '+970'),
  Country(name: 'Panama', flag: '🇵🇦', code: 'PA', dialCode: '+507'),
  Country(name: 'Papua New Guinea', flag: '🇵🇬', code: 'PG', dialCode: '+675'),
  Country(name: 'Paraguay', flag: '🇵🇾', code: 'PY', dialCode: '+595'),
  Country(name: 'Peru', flag: '🇵🇪', code: 'PE', dialCode: '+51'),
  Country(name: 'Philippines', flag: '🇵🇭', code: 'PH', dialCode: '+63'),
  Country(name: 'Poland', flag: '🇵🇱', code: 'PL', dialCode: '+48'),
  Country(name: 'Portugal', flag: '🇵🇹', code: 'PT', dialCode: '+351'),
  Country(name: 'Qatar', flag: '🇶🇦', code: 'QA', dialCode: '+974'),
  Country(name: 'Romania', flag: '🇷🇴', code: 'RO', dialCode: '+40'),
  Country(name: 'Russia', flag: '🇷🇺', code: 'RU', dialCode: '+7'),
  Country(name: 'Rwanda', flag: '🇷🇼', code: 'RW', dialCode: '+250'),
  Country(
    name: 'Saint Kitts and Nevis',
    flag: '🇰🇳',
    code: 'KN',
    dialCode: '+1',
  ),
  Country(name: 'Saint Lucia', flag: '🇱🇨', code: 'LC', dialCode: '+1'),
  Country(name: 'Saint Vincent', flag: '🇻🇨', code: 'VC', dialCode: '+1'),
  Country(name: 'Samoa', flag: '🇼🇸', code: 'WS', dialCode: '+685'),
  Country(name: 'San Marino', flag: '🇸🇲', code: 'SM', dialCode: '+378'),
  Country(
    name: 'Sao Tome and Principe',
    flag: '🇸🇹',
    code: 'ST',
    dialCode: '+239',
  ),
  Country(name: 'Saudi Arabia', flag: '🇸🇦', code: 'SA', dialCode: '+966'),
  Country(name: 'Senegal', flag: '🇸🇳', code: 'SN', dialCode: '+221'),
  Country(name: 'Serbia', flag: '🇷🇸', code: 'RS', dialCode: '+381'),
  Country(name: 'Seychelles', flag: '🇸🇨', code: 'SC', dialCode: '+248'),
  Country(name: 'Sierra Leone', flag: '🇸🇱', code: 'SL', dialCode: '+232'),
  Country(name: 'Singapore', flag: '🇸🇬', code: 'SG', dialCode: '+65'),
  Country(name: 'Slovakia', flag: '🇸🇰', code: 'SK', dialCode: '+421'),
  Country(name: 'Slovenia', flag: '🇸🇮', code: 'SI', dialCode: '+386'),
  Country(name: 'Solomon Islands', flag: '🇸🇧', code: 'SB', dialCode: '+677'),
  Country(name: 'Somalia', flag: '🇸🇴', code: 'SO', dialCode: '+252'),
  Country(name: 'South Africa', flag: '🇿🇦', code: 'ZA', dialCode: '+27'),
  Country(name: 'South Korea', flag: '🇰🇷', code: 'KR', dialCode: '+82'),
  Country(name: 'South Sudan', flag: '🇸🇸', code: 'SS', dialCode: '+211'),
  Country(name: 'Spain', flag: '🇪🇸', code: 'ES', dialCode: '+34'),
  Country(name: 'Sri Lanka', flag: '🇱🇰', code: 'LK', dialCode: '+94'),
  Country(name: 'Sudan', flag: '🇸🇩', code: 'SD', dialCode: '+249'),
  Country(name: 'Suriname', flag: '🇸🇷', code: 'SR', dialCode: '+597'),
  Country(name: 'Sweden', flag: '🇸🇪', code: 'SE', dialCode: '+46'),
  Country(name: 'Switzerland', flag: '🇨🇭', code: 'CH', dialCode: '+41'),
  Country(name: 'Syria', flag: '🇸🇾', code: 'SY', dialCode: '+963'),
  Country(name: 'Taiwan', flag: '🇹🇼', code: 'TW', dialCode: '+886'),
  Country(name: 'Tajikistan', flag: '🇹🇯', code: 'TJ', dialCode: '+992'),
  Country(name: 'Tanzania', flag: '🇹🇿', code: 'TZ', dialCode: '+255'),
  Country(name: 'Thailand', flag: '🇹🇭', code: 'TH', dialCode: '+66'),
  Country(name: 'Togo', flag: '🇹🇬', code: 'TG', dialCode: '+228'),
  Country(name: 'Tonga', flag: '🇹🇴', code: 'TO', dialCode: '+676'),
  Country(
    name: 'Trinidad and Tobago',
    flag: '🇹🇹',
    code: 'TT',
    dialCode: '+1',
  ),
  Country(name: 'Tunisia', flag: '🇹🇳', code: 'TN', dialCode: '+216'),
  Country(name: 'Turkey', flag: '🇹🇷', code: 'TR', dialCode: '+90'),
  Country(name: 'Turkmenistan', flag: '🇹🇲', code: 'TM', dialCode: '+993'),
  Country(name: 'Tuvalu', flag: '🇹🇻', code: 'TV', dialCode: '+688'),
  Country(name: 'Uganda', flag: '🇺🇬', code: 'UG', dialCode: '+256'),
  Country(name: 'Ukraine', flag: '🇺🇦', code: 'UA', dialCode: '+380'),
  Country(
    name: 'United Arab Emirates',
    flag: '🇦🇪',
    code: 'AE',
    dialCode: '+971',
  ),
  Country(name: 'Uruguay', flag: '🇺🇾', code: 'UY', dialCode: '+598'),
  Country(name: 'Uzbekistan', flag: '🇺🇿', code: 'UZ', dialCode: '+998'),
  Country(name: 'Vanuatu', flag: '🇻🇺', code: 'VU', dialCode: '+678'),
  Country(name: 'Vatican City', flag: '🇻🇦', code: 'VA', dialCode: '+379'),
  Country(name: 'Venezuela', flag: '🇻🇪', code: 'VE', dialCode: '+58'),
  Country(name: 'Vietnam', flag: '🇻🇳', code: 'VN', dialCode: '+84'),
  Country(name: 'Yemen', flag: '🇾🇪', code: 'YE', dialCode: '+967'),
  Country(name: 'Zambia', flag: '🇿🇲', code: 'ZM', dialCode: '+260'),
  Country(name: 'Zimbabwe', flag: '🇿🇼', code: 'ZW', dialCode: '+263'),

  // Additional territories and dependencies
  Country(name: 'Hong Kong', flag: '🇭🇰', code: 'HK', dialCode: '+852'),
  Country(name: 'Macau', flag: '🇲🇴', code: 'MO', dialCode: '+853'),
  Country(name: 'Puerto Rico', flag: '🇵🇷', code: 'PR', dialCode: '+1'),
  Country(name: 'American Samoa', flag: '🇦🇸', code: 'AS', dialCode: '+1'),
  Country(name: 'Guam', flag: '🇬🇺', code: 'GU', dialCode: '+1'),
  Country(
    name: 'U.S. Virgin Islands',
    flag: '🇻🇮',
    code: 'VI',
    dialCode: '+1',
  ),
  Country(name: 'Réunion', flag: '🇷🇪', code: 'RE', dialCode: '+262'),
  Country(name: 'Martinique', flag: '🇲🇶', code: 'MQ', dialCode: '+596'),
  Country(name: 'Guadeloupe', flag: '🇬🇵', code: 'GP', dialCode: '+590'),
  Country(name: 'French Guiana', flag: '🇬🇫', code: 'GF', dialCode: '+594'),
  Country(name: 'French Polynesia', flag: '🇵🇫', code: 'PF', dialCode: '+689'),
  Country(name: 'New Caledonia', flag: '🇳🇨', code: 'NC', dialCode: '+687'),
  Country(name: 'Faroe Islands', flag: '🇫🇴', code: 'FO', dialCode: '+298'),
  Country(name: 'Greenland', flag: '🇬🇱', code: 'GL', dialCode: '+299'),
  Country(name: 'Gibraltar', flag: '🇬🇮', code: 'GI', dialCode: '+350'),
  Country(name: 'Bermuda', flag: '🇧🇲', code: 'BM', dialCode: '+1'),
  Country(name: 'Cayman Islands', flag: '🇰🇾', code: 'KY', dialCode: '+1'),
  Country(
    name: 'British Virgin Islands',
    flag: '🇻🇬',
    code: 'VG',
    dialCode: '+1',
  ),
  // Would you like me to continue with more countries? Let me know!
];
